local_backend: true
publish_mode: editorial_workflow

backend:
  name: git-gateway
  repo: luigimass/hugo-decap
  branch: main
  identity_url: https://auth.decapbridge.com/sites/68a8cd5c-f30e-44bf-ab76-4815eea56454
  gateway_url: https://gateway.decapbridge.com

  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://hugo-decap-net.netlify.app

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content"
    path: "{{lang}}/posts/{{slug}}"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Language"
        name: "lang"
        widget: "select"
        options: ["it", "en"]
        default: "it"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Date"
        name: "date"
        widget: "datetime"

      - label: "Featured Image"
        name: "image"
        widget: "image"

      - label: "Excerpt"
        name: "excerpt"
        widget: "text"

      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/it/_index.md"
        label: "Homepage (IT)"
        name: "home_it"
        fields:
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Hero Text", name: "hero", widget: "text" }
          - {
              label: "CTA",
              name: "cta",
              widget: "object",
              fields:
                [
                  { label: "Testo Bottone", name: "text", widget: "string" },
                  { label: "Link Bottone", name: "link", widget: "string" },
                ],
            }

      - file: "content/en/_index.md"
        label: "Homepage (EN)"
        name: "home_en"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Text", name: "hero", widget: "text" }
          - {
              label: "CTA",
              name: "cta",
              widget: "object",
              fields:
                [
                  { label: "Button Text", name: "text", widget: "string" },
                  { label: "Button Link", name: "link", widget: "string" },
                ],
            }

      - file: "content/it/about.md"
        label: "About Page (IT)"
        name: "about_it"
        fields:
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Contenuto", name: "body", widget: "markdown" }

      - file: "content/en/about.md"
        label: "About Page (EN)"
        name: "about_en"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
